<?php

namespace App\Models\System;

use Illuminate\Database\Eloquent\Model;
use Sofa\Eloquence\Eloquence;
use Sofa\Eloquence\Mappable;

class TenantInfo extends Model
{
    use Eloquence, Mappable;

    protected $connection = 'tenant_admin';
    protected $table = '업체정보';
    protected $primaryKey = '도메인';
    protected $guarded = [];
    public $incrementing = false;
    public $timestamps = false;

    protected $maps = [
        'domain'                     => '도메인',
        'password'                   => '비밀번호_암호화',
        'name'                       => '업체명',
        'person_in_charge'           => '담당자',
        'ceo_name'                   => '대표자명',
        'business_no'                => '사업자등록번호',
        'business_type'              => '업태',
        'business_category'          => '종목',
        'payment_type'               => '결제유형',
        'telephone'                  => '대표전화',
        'mobile'                     => '휴대폰',
        'email'                      => '이메일',
        'homepage'                   => '홈페이지',
        'address1'                   => '주소1',
        'address2'                   => '주소2',
        'postcode'                   => '우편번호',
        'code'                       => '업체코드',
        'service_type'               => '서비스종류',
        'service_price'              => '서비스금액',
        'parcel_code'                => '택배사코드',
        'standard_parcel_cost'       => '기본택배비',
        'prepaid_parcel_cost'        => '선불택배비',
        'additional_parcel_cost'     => '도서산간추가택배비',
        'parcel_cost_calculate_type' => '정산구분',
        'cj_parcel_linkage'          => '대한통운사용여부',
        'cj_parcel_id'               => '대한통운아이디',
        'epost_parcel_linkage'       => '우체국연동사용여부',
        'use_db_mirror'              => 'DB미러링사용여부',
        'sms'                        => '문자',
        'sms2'                       => '문자2',
        'mms'                        => '장문자',
        'sender_registered'          => '발신번호등록여부',
        'cs_app_expire_at'           => 'CS프로그램만료일자',
        'callstar_port'              => '콜스타포트번호',
        'stock_service_flag'         => '신재고사용여부',
        'free_stock_service'         => '재고무료사용여부',
        'use_advanced_stock_service' => '상품별재고관리기능사용',
        'order_merged_at'            => '묶음정리홀딩',
        'manage_company_name'        => '관리업체명',
        'calculated_at'              => '미발송통계홀딩',
        'pos_domain'                 => 'POS도메인',
        'pos_api_code'               => 'POSAPI코드',
        'merged_to'                  => '묶음정리위치',
        'merged_by'                  => '묶음정리작업자',
        'paid_at'                    => '결재일',
        'created_at'                 => '등록일자',
        'updated_at'                 => '최종수정일자',
        'pos_api_code_generated_at'  => 'POSAPI갱신일시',
        'order_collected_at'         => '주문입력작업자',
        'db_secured_at'              => 'DB비밀번호갱신일자',
        'product_registered_at'      => '상품등록홀딩',
        'last_merged_at'             => '마지막묶음정리홀딩',
        'secured_at'                 => '보안설정일자',
        'auto_order_collected_at'    => '가져오기홀딩',
        'memo'                       => '비고',
        'active'                     => '등록상태'
    ];
    protected $appends = [
        'domain',
        'password',
        'name',
        'person_in_charge',
        'ceo_name',
        'business_no',
        'business_type',
        'business_category',
        'payment_type',
        'telephone',
        'mobile',
        'email',
        'homepage',
        'address1',
        'address2',
        'postcode',
        'code',
        'service_type',
        'service_price',
        'parcel_code',
        'standard_parcel_cost',
        'prepaid_parcel_cost',
        'additional_parcel_cost',
        'parcel_cost_calculate_type',
        'cj_parcel_linkage',
        'cj_parcel_id',
        'epost_parcel_linkage',
        'use_db_mirror',
        'sms',
        'sms2',
        'mms',
        'sender_registered',
        'cs_app_expire_at',
        'callstar_port',
        'stock_service_flag',
        'free_stock_service',
        'use_advanced_stock_service',
        'order_merged_at',
        'manage_company_name',
        'calculated_at',
        'pos_domain',
        'pos_api_code',
        'merged_to',
        'merged_by',
        'paid_at',
        'created_at',
        'updated_at',
        'pos_api_code_generated_at',
        'order_collected_at',
        'db_secured_at',
        'product_registered_at',
        'last_merged_at',
        'secured_at',
        'auto_order_collected_at',
        'memo',
        'active'
    ];
    protected $hidden = [
        '도메인',
        '비밀번호_암호화',
        '업체명',
        '담당자',
        '대표자명',
        '사업자등록번호',
        '업태',
        '종목',
        '결제유형',
        '대표전화',
        '휴대폰',
        '이메일',
        '홈페이지',
        '주소1',
        '주소2',
        '우편번호',
        '업체코드',
        '서비스종류',
        '서비스금액',
        '택배사코드',
        '기본택배비',
        '선불택배비',
        '도서산간추가택배비',
        '정산구분',
        '대한통운사용여부',
        '대한통운아이디',
        '우체국연동사용여부',
        'DB미러링사용여부',
        '문자',
        '문자2',
        '장문자',
        '발신번호등록여부',
        'CS프로그램만료일자',
        '콜스타포트번호',
        '신재고사용여부',
        '재고무료사용여부',
        '상품별재고관리기능사용',
        '묶음정리홀딩',
        '관리업체명',
        '미발송통계홀딩',
        'POS도메인',
        'POSAPI코드',
        '묶음정리위치',
        '묶음정리작업자',
        '결재일',
        '등록일자',
        '최종수정일자',
        'POSAPI갱신일시',
        '주문입력작업자',
        'DB비밀번호갱신일자',
        '상품등록홀딩',
        '마지막묶음정리홀딩',
        '보안설정일자',
        '가져오기홀딩',
        '비고',
        '등록상태'
    ];
}
